INSERT INTO airlines VALUES (1, 'Lion Air');
INSERT INTO airlines VALUES (2, 'Batik Air');
INSERT INTO airlines VALUES (3, 'Citilink');
INSERT INTO airlines VALUES (4, 'Garuda Indonesia');
INSERT INTO airlines VALUES (5, 'NAM Air');
INSERT INTO airlines VALUES (6, 'Sempati Air');
INSERT INTO airlines VALUES (7, 'Susi Air');
INSERT INTO airlines VALUES (8, 'Sriwijaya Air');
INSERT INTO airlines VALUES (9, 'Garuda Indonesia');
INSERT INTO airlines VALUES (10, 'Citilink');
INSERT INTO airlines VALUES (11, 'Lion Air');
INSERT INTO airlines VALUES (12, 'JetStar Asia');
INSERT INTO airlines VALUES (13, 'Air Asia');
INSERT INTO airlines VALUES (14, 'Air Asia');
INSERT INTO airlines VALUES (15, 'Nok Air');
INSERT INTO airlines VALUES (16, 'VieJet Air');
INSERT INTO airlines VALUES (17, 'JetStar Air');
INSERT INTO airlines VALUES (18, 'Qatar Airways');
INSERT INTO airlines VALUES (19, 'Air China');
INSERT INTO airlines VALUES (20, 'Philippine Airline');
INSERT INTO airlines VALUES (21, 'Citilink');
INSERT INTO airlines VALUES (22, 'Air Asia');
INSERT INTO airlines VALUES (23, 'Lion Air');
INSERT INTO airlines VALUES (24, 'Lion Air');
INSERT INTO airlines VALUES (25, 'Singapore Airlines');
INSERT INTO airlines VALUES (26, 'Turkish Airlines');
INSERT INTO airlines VALUES (27, 'Emirates');
INSERT INTO airlines VALUES (28, 'Korean Air');
INSERT INTO airlines VALUES (29, 'Swiss International Air Lines');
INSERT INTO airlines VALUES (30, 'Air France');
INSERT INTO airlines VALUES (31, 'Thai Airways');
INSERT INTO airlines VALUES (32, 'Cathay Pacific');
INSERT INTO airlines VALUES (33, 'ANA All Nippon Airways');
INSERT INTO airlines VALUES (34, 'British Airways');
INSERT INTO airlines VALUES (35, 'Qantas');
INSERT INTO airlines VALUES (36, 'Etihad Airways');
INSERT INTO airlines VALUES (37, 'Lufthansa');
INSERT INTO airlines VALUES (38, 'Delta Air Lines');
INSERT INTO airlines VALUES (39, 'United Airlines');
INSERT INTO airlines VALUES (40, 'American Airlines');
INSERT INTO airlines VALUES (41, 'China Southern Airlines');
INSERT INTO airlines VALUES (42, 'Ryanair');
INSERT INTO airlines VALUES (43, 'KLM Royal Dutch Airlines');
INSERT INTO airlines VALUES (44, 'Turkish Airlines');
INSERT INTO airlines VALUES (45, 'Air Canada');
INSERT INTO airlines VALUES (46, 'Finnair');
INSERT INTO airlines VALUES (47, 'South African Airways');
INSERT INTO airlines VALUES (48, 'Malaysia Airlines');
INSERT INTO airlines VALUES (49, 'Air India');
INSERT INTO airlines VALUES (50, 'Emirates');