insert into bandara values ('CGK', 'Bandar Udara Internasional Soekarno–Hatta', 'Tangerang, Banten, Indonesia', 'contact.center@angkasapura2.co.id', '622155912648');
insert into bandara values ('SUB', 'Bandar Udara Internasional Juanda', 'Jalan Ir. Haji Juanda, Surabaya, Indonesia', 'cc172@ap1.co.id', '62312986200');
insert into bandara values ('JOG', 'Bandar Udara Internasional Adisucipto', 'Maguwoharjo, Daerah Istimewa Yogyakarta, Indonesia', 'humas.jog@ap1.co.id', '62274484261');
insert into bandara values ('BTJ', 'Bandar Udara Internasional Sultan Iskandar Muda', 'Blang Bintang, Aceh Besar, Indonesia', 'contact.center@angkasapura2.co.id', '6265121341');
insert into bandara values ('DPS', 'Bandar Udara Internasional Ngurah Rai', 'Kelurahan Tuban, Bali, Indonesia', 'cc172@ap1.co.id', '623619351011');
insert into bandara values ('DJJ', 'Bandar Udara Internasional Sentani', 'Kel. Sentani Kota, Jayapura Papua, Indonesia', 'cc172@ap1.co.id', '62967591168');
insert into bandara values ('KOE', 'Bandar Udara El Tari', 'Kupang, Nusa Tenggara Timur, Indonesia', 'pkbl_pst@ap1.co.id', '62380882031');
insert into bandara values ('PLM', 'Bandar Udara Internasional Sultan Mahmud Badaruddin II', 'Kota Palembang, Sumatra Selatan, Indonesia', 'contact.center@angkasapura2.co.id', '62711385000');
insert into bandara values ('MDC', 'Bandar Udara Internasional Sam Ratulangi', 'Manado, Sulawesi Utara, Indonesia', 'cc172@ap1.co.id', '62431814320');
insert into bandara values ('AAP', 'Bandar Udara Internasional Aji Pangeran Tumenggung Pranoto', 'Jalan Samarinda Utara, Sungai Siring, Samarinda', 'humas@aptpranotoairport.id', '625412831593');
insert into bandara values ('BIK', 'Bandar Udara Internasional Frans Kaisiepo', 'Biak, Papua, Indonesia', 'humas.bik@ap1.co.id', '6298122555');
insert into bandara values ('SIN', 'Singapore Changi Airport', 'Changi, East Region, Singapore', 'enquiry@changiairport.com', '6565956868');
insert into bandara values ('KUL', 'Kuala Lumpur International Airport', 'Sepang, Selangor, Malaysia', 'CARE@malaysiaairports.com.my', '60387762000');
insert into bandara values ('MNL', 'Ninoy Aquino International Airport', 'Parañaque and Pasay, Metro Manila, Philippines', 'info@miaa.gov.ph', '6328771109');
insert into bandara values ('BKK', 'Suvarnabhumi Airport', 'Racha Thewa, Bangkok, Thailand', 'aotpr@airportthai.co.th', '6621321888');
insert into bandara values ('IST', 'Istanbul Airport', 'Tayakadın, Arnavutköy, Istanbul', 'ist@igairport.aero', '904441442');
insert into bandara values ('SVO', 'Sheremetyevo International Airport', 'Khimki, Moscow Oblast, Russia', 'info@sheremetyevo-airport.ru', '74955786565');
insert into bandara values ('PEK', 'Beijing Capital International Airport', 'Shunyi District, Beijing, China', 'service@bcia.com.cn', '861096158');
insert into bandara values ('LAX', 'Los Angeles International Airport', 'Westchester, California, United States', 'infoline@lawa.org', '8554635252');
insert into bandara values ('ICN', 'Incheon International Airport', 'Jung District, Incheon, South Korea', 'find119@airport.kr', '8215772600');
insert into bandara values ('SYD', 'Sydney Airport', 'Mascot, New South Wales, Australia', 'info@sydneyairport.com.au', '61296679111');
insert into bandara values ('JFK', 'John F. Kennedy International Airport', 'Queens, New York, United States', 'info@panynj.gov', '7182443501');
insert into bandara values ('DXB', 'Dubai International Airport', 'Garhoud, Dubai, United Arab Emirates', 'customer.relations@dubaiairports.ae', '97142188888');
insert into bandara values ('FRA', 'Frankfurt Airport', 'Frankfurt, Hesse, Germany', 'info@fraport.de', '4969750');
insert into bandara values ('AMS', 'Amsterdam Airport Schiphol', 'Haarlemmermeer, North Holland, Netherlands', 'schipholinfo@schiphol.nl', '31206541911');
insert into bandara values ('CDG', 'Charles de Gaulle Airport', 'Roissy-en-France, Île-de-France, France', 'accueil.client@adp.fr', '33148621212');
insert into bandara values ('FCO', 'Leonardo da Vinci–Fiumicino Airport', 'Fiumicino, Lazio, Italy', 'customer.relations@adr.it', '3906659591');
insert into bandara values ('HND', 'Haneda Airport', 'Ota, Tokyo, Japan', 'airport-int@tokyo-airport-bldg.co.jp', '81357571700');
insert into bandara values ('HKG', 'Hong Kong International Airport', 'Chek Lap Kok, Islands District, Hong Kong', 'enquiry@hkairport.com', '85221818888');
insert into bandara values ('ORD', 'O `Hare International Airport', 'Chicago, Illinois, United States', 'feedback@flychicago.com', '17732244000');
insert into bandara values ('ATL', 'Hartsfield–Jackson Atlanta International Airport', 'Atlanta, Georgia, United States', 'info@atl.com', '17708973000');
insert into bandara values ('DEN', 'Denver International Airport', 'Denver, Colorado, United States', 'info@flydenver.com', '13032900000');
insert into bandara values ('LHR', 'London Heathrow Airport', 'Hillingdon, London, United Kingdom', 'lhr_customer_relations@heathrow.com', '448709340000');
insert into bandara values ('SFO', 'San Francisco International Airport', 'San Mateo County, California, United States', 'info@flysfo.com', '18007376736');
insert into bandara values ('UPG', 'Sultan Hasanuddin International Airport (UPG)', 'Makassar, Sulawesi Selatan', 'info@hasanuddin-airport.co.id', '62411540777');
insert into bandara values ('BTH', 'Hang Nadim International Airport (BTH)', 'Batam, Kepulauan Riau', 'info@hangnadim-airport.com', '62778404040');
insert into bandara values ('BPN', 'Sultan Aji Muhammad Sulaiman Airport (BPN)', 'Balikpapan, Kalimantan Timur', 'info@balikpapan-airport.com', '62542522185');
insert into bandara values ('KNO', 'Kualanamu International Airport (KNO)', 'Medan, Sumatera Utara', 'info@kualanamu-airport.com', '62615666111');
insert into bandara values ('PDG', 'Minangkabau International Airport (PDG)', 'Padang, Sumatera Barat', 'info@minangkabau-airport.co.id', '62751808000');
insert into bandara values ('PNK', 'Supadio International Airport (PNK)', 'Pontianak, Kalimantan Barat', 'info@supadio-airport.co.id', '625617403000');
insert into bandara values ('BDO', 'Husein Sastranegara International Airport (BDO)', 'Bandung, Jawa Barat', 'bandara@angkasapura2.co.id', '622266008808');
insert into bandara values ('PKU', 'Sultan Syarif Kasim II International Airport', 'Pekanbaru, Riau', 'info@skasim2-airport.co.id', '62761611300');
insert into bandara values ('SRG', 'Achmad Yani International Airport (SRG)', 'Semarang, Jawa Tengah', 'info@achmadyani-airport.co.id', '622438107000');
insert into bandara values ('AMQ', 'Pattimura Airport (AMQ)', 'Ambon, Maluku', 'info@pattimura-airport.co.id', '62911356132');
insert into bandara values ('BDJ', 'Syamsudin Noor Int`l Airport (BDJ)', 'Banjarmasin, Kalimantan Selatan', 'info@syamsudinnoor-airport.com', '62511610550');
insert into bandara values ('DMM', 'King Fahd International Airport', 'Dammam, Saudi Arabia', 'info@dmm-airport.com', '966138245678');
insert into bandara values ('TPE', 'Taiwan Taoyuan International Airport', 'Dayuan District, Taoyuan City, Taiwan', 'taoyuan@tymail.gov.tw', '88633189999');
insert into bandara values ('NRT', 'Narita International Airport', 'Narita, Chiba, Japan', 'cs@narita-airport.jp', '81476353544');
insert into bandara values ('YYZ', 'Bandar Udara Internasional Toronto Pearson', 'Toronto, Ontario', 'toronto_pearson@example.com', '123456789');
insert into bandara values ('YVR', 'Bandar Udara Internasional Vancouver', 'Vancouver, British Columbia', 'vancouver_airport@example.com', '987654321');
