INSERT INTO menu_paket_makanan VALUES (1, 'Bircher Muesli', '100000', 'Sajian Bircher Muesli yang ditaburi biji labu, kismis, dan potongan apel');
INSERT INTO menu_paket_makanan VALUES (2, 'Lontong Medan', '75000', 'Sajian dengan telur pindang, ayam suwir, orek tahu buncis, dan sayur labu siam yang gurih');
INSERT INTO menu_paket_makanan VALUES (3, 'Dragon Fruit with Smoothies with Granola', '90000', 'Kesegaran smoothie buah naga ditaburi potongan kiwi, pisang, chia seeds, granola serta buah stroberi segar');
INSERT INTO menu_paket_makanan VALUES (4, 'Biryani Rice with Lamb', '95000', 'Sajian Nasi Biryani dengan daging kambing yang gurih, kentang, kembang kol dengan bumbu kunyit, saus hijau, saus merah dan bawang');
INSERT INTO menu_paket_makanan VALUES (5, 'Egg Dishes', '50000', 'Telur yang dihidangkan sesuai dengan selera Anda, Kami sajikan hangat dengan tumis sayuran dan potongan kentang');
INSERT INTO menu_paket_makanan VALUES (6, 'Nasi Goreng Spesial', '65000', 'Nasi Goreng Special disajikan dengan tumis udang balado, ayam goreng mentega, telur mata sapi dan sambal bajak');
INSERT INTO menu_paket_makanan VALUES (7, 'Nasi Padang Ayam Bakar', '70000', 'Ayam bakar disajikan dengan nasi daun jeruk, tumis pucuk labu kecombrang, dan sambal hijau');
INSERT INTO menu_paket_makanan VALUES (8, 'Pepes Tahu with Omelet', '35000', 'Tahu yang dibalut dengan bumbu pepes kemudian dikukus disajikan bersama telur dadar serta tumisan brokoli, wortel dan buncis');
INSERT INTO menu_paket_makanan VALUES (9, 'Fettuccine Pesto & Grilled mushroom', '55000', 'Terdiri dari fettuccini yang dimasak dengan saus pesto, lebih nikmat karena dihidangkan dengan paprika dan jamur champignon panggang, serta asparagus dan tomat ceri');
INSERT INTO menu_paket_makanan VALUES (10, 'Nasi Padang Rendang Daging', '75000', 'Daging Rendang disajikan dengan nasi daun jeruk, tumis jantung pisang, dan sambal hijau');
INSERT INTO menu_paket_makanan VALUES (11, 'Beef Hayashi', '66000', 'Daging hayashi yang disajikan dengan nasi hangat dan ditaburi irisan daun bawang');
INSERT INTO menu_paket_makanan VALUES (12, 'Omelet', '45000', 'Telur dadar yang disajikan dengan sosis ayam panggang, wortel, jagung, dan kacang poloing serta potongan kentang panggang yang ditaburi peterseli');
INSERT INTO menu_paket_makanan VALUES (13, 'Lacto Ovo Meal', '51000', 'Dihidangkan dengan tumis paprika dan ditaburi irisan buah zaitun hitam kemudian disiram dengan saus tomat akan menyempurkan kelezatan dari hidangan ini');
INSERT INTO menu_paket_makanan VALUES (14, 'Poach Salmon, mashed potato, and Asparagus', '80000', 'Kombinasi ikan salmon yang direbus akan membawa perpaduan rasa dan tekstur yang unik di lidah Anda');
INSERT INTO menu_paket_makanan VALUES (15, 'Nasi Kuning Nusantara', '57000', 'Nasi Kuning Nusantara dengan ayam bumbu rujak, orek tempe, dan orak arik sayur');
INSERT INTO menu_paket_makanan VALUES (16, 'Nasi Tutug Oncom', '45000', 'Nasi Tutug Oncom adalah nasi atau sangu yang ditumbuk (ditutug) bersama oncom bakar yang berasal dari Tasikmalaya, Jawa Barat');
INSERT INTO menu_paket_makanan VALUES (17, 'Honey Glazed Salmon with Quinoa', '53000', 'Salmon fillet disiram dengan saus teriyaki, disajikan dengan tumisan wortel, timun, labu, daikon ditambah salad quinoa, potongan cabai, daun bawang, dan edamame kukus');
INSERT INTO menu_paket_makanan VALUES (18, 'Yang Nyomu Chicken', '125000', 'Set menu Korea berisi ayam yang nyomu yang gurih ala korea disajikan dengan tumis jamur shitake dan zucchini');
INSERT INTO menu_paket_makanan VALUES (19, 'Salmon Kankitsu-yaki Sauce Kuhaku-an', '130000', 'Lezatnya salmon kukus ala Jepang yang dilapisi dengan kulit tahu, disajikan dengan nasi khas Jepang, saus Kuhaku dan sup miso');
INSERT INTO menu_paket_makanan VALUES (20, 'Blueberry Pancake with Maple Syrup and Strawberry Compote', '75000', 'Lembutnya pancake blueberry yang disiram dengan sirup maple dan saus stroberi');
INSERT INTO menu_paket_makanan VALUES (21, 'Spaghetti Bolognese', '70000', 'Pasta spaghetti al dente dengan saus bolognese daging sapi dan taburan keju parmesan');
INSERT INTO menu_paket_makanan VALUES (22, 'Fish and Chips', '80000', 'Potongan ikan goreng tepung yang renyah disajikan dengan kentang goreng dan saus tartar');
INSERT INTO menu_paket_makanan VALUES (23, 'Chicken Parmigiana', '85000', 'Potongan ayam panggang dengan saus tomat, keju mozzarella, dan basil, disajikan dengan spaghetti');
INSERT INTO menu_paket_makanan VALUES (24, 'Beef Wellington', '120000', 'Potongan daging sapi yang dibalut dengan pastry dan saus mushroom, dipanggang hingga kecokelatan');
INSERT INTO menu_paket_makanan VALUES (25, 'Sushi Platter', '90000', 'Platter berisi berbagai jenis sushi seperti nigiri, maki, dan sashimi');
INSERT INTO menu_paket_makanan VALUES (26, 'Beef Burger with Fries', '75000', 'Burger daging sapi yang juicy dengan saus, keju, sayuran segar, dan disajikan dengan kentang goreng');
INSERT INTO menu_paket_makanan VALUES (27, 'Caesar Salad with Grilled Chicken', '65000', 'Salad segar dengan potongan ayam panggang, crouton, parmesan, dan dressing Caesar');
INSERT INTO menu_paket_makanan VALUES (28, 'Pad Thai', '70000', 'Mi kuning goreng ala Thailand dengan udang, tahu, kacang, dan bumbu khas');
INSERT INTO menu_paket_makanan VALUES (29, 'Chicken Satay with Peanut Sauce', '60000', 'Sate ayam yang dipanggang dengan bumbu kacang yang gurih, disajikan dengan lontong dan sayuran');
INSERT INTO menu_paket_makanan VALUES (30, 'Beef Stroganoff', '95000', 'Potongan daging sapi yang dimasak dengan saus krim, jamur, dan bawang bombay, disajikan dengan nasi atau pasta');
INSERT INTO menu_paket_makanan VALUES (31, 'Lobster Thermidor', '250000', 'Lobster panggang dengan saus keju dan mustard, disajikan dengan kentang gratin');
INSERT INTO menu_paket_makanan VALUES (32, 'Miso Soup with Tofu and Seaweed', '30000', 'Sup khas Jepang dengan miso, tahu, dan rumput laut');
INSERT INTO menu_paket_makanan VALUES (33, 'Peking Duck', '180000', 'Bebek peking yang dipanggang hingga kulitnya renyah, disajikan dengan pancake dan saus hoisin');
INSERT INTO menu_paket_makanan VALUES (34, 'Chicken Tikka Masala with Naan', '85000', 'Potongan ayam panggang dengan saus masala krim yang kaya rempah, disajikan dengan roti naan');
INSERT INTO menu_paket_makanan VALUES (35, 'Shrimp Scampi', '90000', 'Udang segar yang dimasak dengan saus lemon butter, bawang putih, dan parsley, disajikan dengan pasta');
INSERT INTO menu_paket_makanan VALUES (36, 'Vegan Buddha Bowl', '75000', 'Bowl berisi nasi merah, sayuran panggang, hummus, alpukat, dan biji-bijian');
INSERT INTO menu_paket_makanan VALUES (37, 'Gyudon', '70000', 'Nasi dengan potongan daging sapi yang dimasak dengan saus mirin, kecap manis, dan bawang bombay');
INSERT INTO menu_paket_makanan VALUES (38, 'Chicken Alfredo', '80000', 'Potongan ayam panggang dengan saus krim keju Parmesan, disajikan dengan pasta');
INSERT INTO menu_paket_makanan VALUES (39, 'Vegetable Curry with Basmati Rice', '65000', 'Sayuran yang dimasak dengan saus kari kental, disajikan dengan nasi basmati');
INSERT INTO menu_paket_makanan VALUES (40, 'Beef Tacos', '70000', 'Taco dengan isian daging sapi, keju, sayuran, dan saus salsa');
INSERT INTO menu_paket_makanan VALUES (41, 'Mushroom Risotto', '85000', 'Nasi Arborio yang dimasak dengan kaldu jamur dan jamur segar, disajikan dengan parmesan parut');
INSERT INTO menu_paket_makanan VALUES (42, 'Grilled Steak with Mashed Potatoes', '120000', 'Steak panggang dengan saus bawang putih, disajikan dengan kentang tumbuk');
INSERT INTO menu_paket_makanan VALUES (43, 'Chicken Caesar Wrap', '65000', 'Gulungan tortilla dengan potongan ayam panggang, selada romaine, parmesan, dan dressing Caesar');
INSERT INTO menu_paket_makanan VALUES (44, 'Eggplant Parmesan', '75000', 'Ikan teri yang digoreng hingga renyah, disajikan dengan nasi, telur ceplok, dan sambal terasi');
INSERT INTO menu_paket_makanan VALUES (45, 'Hawaiian Pizza', '70000', 'Pizza dengan topping daging ham, keju, dan potongan nanas');
INSERT INTO menu_paket_makanan VALUES (46, 'Seafood Paella', '90000', 'Nasi berbumbu kunyit dengan campuran seafood seperti udang, cumi, kerang, dan ikan');
INSERT INTO menu_paket_makanan VALUES (47, 'Vegetable Lasagna', '80000', 'Lasagna dengan lapisan sayuran seperti zucchini, wortel, dan bayam');
INSERT INTO menu_paket_makanan VALUES (48, 'Teriyaki Chicken Bowl', '75000', 'Bowl berisi nasi dengan potongan ayam teriyaki, sayuran, dan telur mata sapi');
INSERT INTO menu_paket_makanan VALUES (49, 'Mongolian Beef', '85000', 'Potongan daging sapi yang dimasak dengan saus manis pedas, bawang bombay, dan jahe');
INSERT INTO menu_paket_makanan VALUES (50, 'Tiramisu', '60000', 'Puding khas Italia dengan lapisan keju mascarpone, kopi, dan cokelat, disajikan dengan taburan bubuk kakao');