INSERT INTO model_pesawat VALUES (1, 'Boeing 737-200', 'Boeing ');
INSERT INTO model_pesawat VALUES (2, 'Boeing 737-500 Winglet', 'Boeing ');
INSERT INTO model_pesawat VALUES (3, 'Next Generation Boeing 737-800', 'Boeing ');
INSERT INTO model_pesawat VALUES (4, 'Boeing 737-800', 'Boeing ');
INSERT INTO model_pesawat VALUES (5, 'Boeing 737-900', 'Boeing ');
INSERT INTO model_pesawat VALUES (6, 'Boeing 737 MAX 8', 'Boeing ');
INSERT INTO model_pesawat VALUES (7, 'Boeing 737 MAX 9', 'Boeing ');
INSERT INTO model_pesawat VALUES (8, 'Boeing 737-900ER', 'Boeing ');
INSERT INTO model_pesawat VALUES (9, 'Boeing 747-8', 'Boeing ');
INSERT INTO model_pesawat VALUES (10, 'Boeing 767', 'Boeing ');
INSERT INTO model_pesawat VALUES (11, 'Boeing 777-300ER', 'Boeing ');
INSERT INTO model_pesawat VALUES (12, 'Boeing 787', 'Boeing ');
INSERT INTO model_pesawat VALUES (13, 'A320neo', 'Airbus');
INSERT INTO model_pesawat VALUES (14, 'A321neo', 'Airbus');
INSERT INTO model_pesawat VALUES (15, 'A320ceo', 'Airbus');
INSERT INTO model_pesawat VALUES (16, 'A330neo', 'Airbus');
INSERT INTO model_pesawat VALUES (17, 'A330-200', 'Airbus');
INSERT INTO model_pesawat VALUES (18, 'A330-300', 'Airbus');
INSERT INTO model_pesawat VALUES (19, 'ATR 72-500', 'ATR');
INSERT INTO model_pesawat VALUES (20, 'ATR 72-600', 'ATR');
INSERT INTO model_pesawat VALUES (21, 'Embraer E175', 'Embraer');
INSERT INTO model_pesawat VALUES (22, 'Embraer E190', 'Embraer');
INSERT INTO model_pesawat VALUES (23, 'Embraer E195', 'Embraer');
INSERT INTO model_pesawat VALUES (24, 'Embraer E190-E2', 'Embraer');
INSERT INTO model_pesawat VALUES (25, 'Embraer E195-E2', 'Embraer');
INSERT INTO model_pesawat VALUES (26, 'Cessna 172 Skyhawk', 'Cessna');
INSERT INTO model_pesawat VALUES (27, 'Cessna 182 Skylane', 'Cessna');
INSERT INTO model_pesawat VALUES (28, 'Cessna 206 Stationair', 'Cessna');
INSERT INTO model_pesawat VALUES (29, 'Bombardier CRJ700', 'Bombardier');
INSERT INTO model_pesawat VALUES (30, 'Bombardier CRJ900', 'Bombardier');
INSERT INTO model_pesawat VALUES (31, 'Bombardier CRJ1000', 'Bombardier');
INSERT INTO model_pesawat VALUES (32, 'DHC-6 Twin Otter', 'De Havilland Canada');
INSERT INTO model_pesawat VALUES (33, 'DHC-8-100 Dash 8', 'De Havilland Canada');
INSERT INTO model_pesawat VALUES (34, 'DHC-8-200 Dash 8', 'De Havilland Canada');
INSERT INTO model_pesawat VALUES (35, 'DHC-8-300 Dash 8', 'De Havilland Canada');
INSERT INTO model_pesawat VALUES (36, 'DHC-8-400 Dash 8', 'De Havilland Canada');
INSERT INTO model_pesawat VALUES (37, 'Sukhoi Superjet 100', 'Sukhoi');
INSERT INTO model_pesawat VALUES (38, 'Antonov An-148', 'Antonov');
INSERT INTO model_pesawat VALUES (39, 'Antonov An-158', 'Antonov');
INSERT INTO model_pesawat VALUES (40, 'Antonov An-225 Mriya', 'Antonov');
INSERT INTO model_pesawat VALUES (41, 'McDonnell Douglas MD-80', 'McDonnell Douglas');
INSERT INTO model_pesawat VALUES (42, 'McDonnell Douglas MD-90', 'McDonnell Douglas');
INSERT INTO model_pesawat VALUES (43, 'McDonnell Douglas MD-11', 'McDonnell Douglas');
INSERT INTO model_pesawat VALUES (44, 'Fokker 50', 'Fokker');
INSERT INTO model_pesawat VALUES (45, 'Fokker 70', 'Fokker');
INSERT INTO model_pesawat VALUES (46, 'Fokker 100', 'Fokker');
INSERT INTO model_pesawat VALUES (47, 'Dornier Do 228', 'Dornier');
INSERT INTO model_pesawat VALUES (48, 'Dornier Do 328', 'Dornier');
INSERT INTO model_pesawat VALUES (49, 'Dornier Do 328JET', 'Dornier');
INSERT INTO model_pesawat VALUES (50, 'Saab 340', 'Saab');