CREATE SEQUENCE Destinasi_sq 
MINVALUE 1 
MAXVALUE 99999999999999999	
START WITH 1 
INCREMENT BY 1;

-- CREATE TABLE Destinasi
CREATE TABLE Destinasi (
    D_ID INT PRIMARY KEY DEFAULT nextval('Destinasi_sq'),
    D_Lokasi_Asal CHAR(3) NOT NULL,
    D_Lokasi_Tujuan CHAR(3) NOT NULL
);
